Vagrant.configure(2) do |config|
  config.vm.boot_timeout = 600

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'hyperv' do |hv|
    hv.cpus = 2
    hv.memory = 2048
  end

  config.vm.provider 'libvirt' do |lv|
    lv.cpus = 2
    lv.memory = 2048
    lv.disk_driver :discard => 'unmap', :detect_zeroes => 'unmap'
    lv.machine_type = 'q35'
    lv.nested = true
    lv.video_type = 'vga'
    lv.input :type => 'tablet', :bus => 'usb'
  end

  config.vm.provider 'vmware_desktop' do |vmd|
    vmd.cpus = 2
    vmd.memory = 2048
    vmd.force_vmware_license = "workstation"
  end
end
